deploymentMode: Distributed

global:
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: MINIO_USER
      valueFrom:
        secretKeyRef:
          name: minio-for-loki-secret
          key: rootUser
    - name: MINIO_PASSWORD
      valueFrom:
        secretKeyRef:
          name: minio-for-loki-secret
          key: rootPassword

loki:
  # Should authentication be enabled
  auth_enabled: false
  # -- Storage config. Providing this will automatically populate all necessary storage configs in the templated config.
  storage:
    # Loki requires a bucket for chunks and the ruler. GEL requires a third bucket for the admin API.
    # Please provide these values if you are using object storage.
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:

      # # MinIO S3 (На обычных серверах)
      # s3: http://api.minio.fillswim.local
      # endpoint: http://api.minio.fillswim.local

      # # MinIO S3 Cluster K8s (Через Ingress)
      # s3: http://api.minio-k8s1-rhel.fillswim.local
      # endpoint: http://api.minio-k8s1-rhel.fillswim.local

      # # MinIO S3 Cluster K8s (Внутри кластера, через Service Cluster IP)
      s3: http://minio.minio.svc.cluster.local:9000
      endpoint: http://minio.minio.svc.cluster.local:9000

      accessKeyId: "${MINIO_USER}"
      secretAccessKey: "${MINIO_PASSWORD}"
      s3ForcePathStyle: true
      insecure: true
      http_config: {}
      backoff_config: {}
      disable_dualstack: false

  useTestSchema: false

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  ingester:
    chunk_encoding: snappy
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h
  compactor:
    retention_enabled: true
    delete_request_store: s3

ingester:
  replicas: 3 # To ensure data durability with replication
querier:
  replicas: 3 # Improve query performance via parallelism
  maxUnavailable: 2
queryFrontend:
  replicas: 3
  maxUnavailable: 1
queryScheduler:
  replicas: 3
distributor:
  replicas: 3
  maxUnavailable: 2
compactor:
  replicas: 3
indexGateway:
  replicas: 3
  maxUnavailable: 1
gateway:
  replicas: 3
resultsCache:
  replicas: 3
chunksCache:
  replicas: 3

bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

singleBinary:
  replicas: 0

# Enable minio for storage
minio:
  enabled: false

# -- Ingress configuration Use either this ingress or the gateway, but not both at once.
# If you enable this, make sure to disable the gateway.
# You'll need to supply authn configuration for your ingress controller.
ingress:
  enabled: true
  ingressClassName: "nginx"
  # -- Hosts configuration for the ingress, passed through the `tpl` function to allow templating
  hosts:
    - loki.fillswim.local
