opentelemetry-collector:
  enabled: true

  config:
    exporters:
      otlphttp/alloy:
        endpoint: http://alloy.alloy.svc.cluster.local:4318
        tls:
          insecure: true
        # sending_queue:
        #   enabled: true


    service:
      pipelines:
        traces:
          # было: [otlp/jaeger, debug, spanmetrics]
          exporters: [otlphttp/alloy, debug, spanmetrics]
          # - otlphttp/alloy

jaeger:
  enabled: false