apiVersion: argoproj.io/v1alpha1
kind: Application

# kubectl apply  -f K8s1-RHEL/applications-non-sync/alma-k8s2/prometheus-alma-k8s2.yaml
# kubectl delete -f K8s1-RHEL/applications-non-sync/alma-k8s2/prometheus-alma-k8s2.yaml

# kubectl -n alloy port-forward svc/alloy 12345:12345
# http://127.0.0.1:12345/graph

metadata:
  name: prometheus-alma-k8s2                                              # Название создаваемого Argo CD application
  namespace: argo-cd                                                      # namespace, в котором будет создаваться Argo CD application
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background

spec:
  project: default

  destination:
    name: kubernetes-admin-alma-k8s2@alma-k8s2                            # Деплой в этот же кластер
    namespace: prometheus                                                 # В какой namespace будет производиться деплой

  sources:
    # - repoURL: "https://prometheus-community.github.io/helm-charts"       # Репозиторий с Helm чартом
    - repoURL: "oci://harbor.fillswim.local/charts/kube-prometheus-stack" # Репозиторий с Helm чартом
      chart: kube-prometheus-stack                                        # Наименование Helm чарта
      targetRevision: 79.0.0                                              # Версия Helm чарта
      helm:
        releaseName: prometheus                                           # Название релиза
        valueFiles:
          - $values/K8s1-RHEL/helm-values/alma-k8s2/prometheus-values-alma-k8s2.yaml.yaml

    - repoURL: "https://github.com/fillswim/ArgoCD.git"                   # Репозиторий с values
      targetRevision: main
      ref: values

    - repoURL: 'https://github.com/fillswim/ArgoCD.git'                   # Репозиторий
      path: "K8s1-RHEL/additions/additions-alma-k8s2/prometheus"          # Относительный путь отслеживаемой папки
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true